pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    def dockerImage = 'node:lts-buster-slim'
                    docker.image(dockerImage).inside('-p 3000:3000') {
                        sh 'npm install'
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    def dockerImage = 'node:lts-buster-slim'
                    docker.image(dockerImage).inside {
                        sh './fahrul_vfwa/scripts/test.sh'
                    }
                }
            }
        }

        stage('Deliver') {
            steps {
                script {
                    def dockerImage = 'node:lts-buster-slim'
                    docker.image(dockerImage).inside {
                        sh './fahrul_vfwa/scripts/deliver.sh'
                    }
                    input message: 'Finished using the web site? Click "Proceed" to continue'
                    sh './fahrul_vfwa/scripts/kill.sh'
                }
            }
        }
    }
}
