pipeline {
    agent any
    
    environment {
        CI = 'true'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: '*/react-app']],
                          userRemoteConfigs: [[url: 'git@github.com:fahrul327/a428-cicd-labs.git']]])
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run Docker') {
            steps {
                sh 'docker run -p 3000:3000 -v $PWD:/app -w /app node:16-buster-slim npm start'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
